import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Notion API: Public auth example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="">
          <h1>Notion API Public integration example</h1>
          <p>
            Use this sample app as an example of how to set up public
            authentication with the Notion API. This sample app uses the{" "}
            <a href="https://github.com/makenotion/notion-sdk-js">
              Notion JavaScript API
            </a>
            .
          </p>
          <p>
            For a complete guide to authorization your Notion integration, read
            the{" "}
            <a href="https://developers.notion.com/docs/authorization">
              Authorization guide
            </a>{" "}
            in the Notion public API docs.
          </p>
          <h2>Auth flow steps from a code perspective</h2>
          <ol>
            <li>Navigate the user to the integration’s authorization URL</li>
            <li>
              Notion redirects the user to the integration’s redirect_uri and
              includes a code parameter
            </li>
            <li>
              The integration sends the code in a POST request to the Notion API
            </li>
            <li>
              Notion responds with an access_token and some additional
              information
            </li>
            <li>The integration stores the access_token for future requests</li>
          </ol>
          <section>
            <h2>Steps from a user's experience</h2>
            <h3>Step 1: Navigate to auth URL</h3>
            <a href={process.env.NOTION_AUTH_URL}>
              Click here to go to auth URL
            </a>
            <p>This will start the public integration auth process.</p>
            <h3>Step 2: Select pages to give access to</h3>
            <p>Complete step 2 on the page you're redirected to. Click "Select Pages" to see the pages available to you in the workspace. Select the pages you want to give the integration access to.</p>
            <h3>Step 3: Submit page selections to be approved</h3>
            <p>When you submit the form on the redirect page, you'll have to click "Allow access".</p>
            <h3>Step 4: See if it worked</h3>
            <p>If access is granted, you'll see the /auth-callback page and the API response will be displayed on the screen. Do not display this information in your app. It is included here to show how authentication works.</p>
            <h3>Step 5: Decide how to store your access_token</h3>
            <p>The access token should be kept in a safe place, like a database.</p>
          </section>
        </div>
      </main>
    </>
  );
}
