import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Notion API: Public auth example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="">
          <h1>Notion API Public integration example</h1>
          <p>
            Use this demo app as an example of how to set up public
            authentication with the Notion API.
          </p>
          <p>
            For a complete guide to authorization your Notion integration, read
            the{" "}
            <a href="https://developers.notion.com/docs/authorization">
              Authorization guide
            </a>{" "}
            in the Notion public API docs.
          </p>
          <h2>Auth flow steps from a code perspective</h2>
          <ol>
            <li>
              Navigate the user to the integration’s authorization URL. The auth
              URL is available through your integration's settings at{" "}
              <a href="https://www.notion.so/my-integrations">
                notion.so/my-integrations
              </a>
              .
            </li>
            <li>
              Notion redirects the user to the integration’s redirect URI and
              includes a <code>code</code> parameter.
            </li>
            <li>
              The integration sends the <code>code</code> in a <code>POST</code>{" "}
              request to the Notion API.
            </li>
            <li>
              Notion responds with an <code>access_token</code> and some
              additional information.
            </li>
            <li>
              The integration code stores the <code>access_token</code> for
              future requests. In this demo, the token is used for an API
              request to test it works but should be stored more securely in
              production-level apps. As a general rule, tokens should not be
              used client-side.
            </li>
          </ol>
          <section>
            <h2>Steps from a user's experience</h2>
            <h3>Step 1: Navigate to auth URL</h3>
            <a href={process.env.NOTION_AUTH_URL}>
              Click here to go to auth URL
            </a>
            <p>This will start the public integration auth process.</p>
            <h3>Step 2: Select pages to give access to</h3>
            <p>
              Complete step 2 on the page you're redirected to. Click "Select
              Pages" to see the pages available to you in the workspace. Select
              the pages you want to give the integration access to.
            </p>
            <h3>Step 3: Submit page selections to be approved</h3>
            <p>
              When you submit the form on the redirect page, you'll have to
              click "Allow access".
            </p>
            <h3>Step 4: See if it worked</h3>
            <p>
              If access is granted, you'll see the <code>/auth-callback</code>{" "}
              page and the API response will be displayed on the screen. Do not
              display this information in your app. It is included here to show
              how authentication works.
            </p>
            <h3>
              Step 5: Decide how to store your <code>access_token</code>
            </h3>
            <p>
              The access token should be kept in a safe place, like a database.
              Do not use it client-side to avoid exposing it.
            </p>
            <p>
              For demo-purposes, you can test your token is valid by clicking
              the "Test API" button after the token has been successfully
              generated. This will my a GET /users requests to the Notion API.
            </p>
          </section>
        </div>
      </main>
    </>
  );
}
